### ISSUE TITLE
calculate dimensions using d3 rather than hardcode

### ISSUE THREAD

**Issue by pragmasoft-ua** [pragmasoft-ukraine/charts-test-app#4]
https://github.com/pragmasoft-ukraine/charts-test-app/blob/master/src/components/SeriesLineChart/index.js#L38

**Comment by qwertypomy** [comment]
https://github.com/pragmasoft-ukraine/charts-test-app/commit/4edae688ab68bb7ebaff6c38334db2bb3e7357fc
